plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

title: Akshat Thukral
description: Engine Programmer | Technical Lead
google_analytics: G-1CS3FTN91C

github_url: https://github.com/codenameone-akshat
linkedin_url: https://www.linkedin.com/in/codenameone/
email: code.akshat.thukral@gmail.com

baseurl: /
url: http://codenameone-akshat.github.io

sass:
  implementation: sass-embedded

incremental: false