title: Akshat Thukral
description: Engine Programmer | Technical Lead
google_analytics: G-1CS3FTN91C
theme: jekyll-theme-hacker

github_url: https://github.com/codenameone-akshat
linkedin_url: https://www.linkedin.com/in/codenameone/
email: code.akshat.thukral@gmail.com